### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by gwpl** [nodebox/nodebox-pyobjc#8]
While researching graph visualization programming libraries, I came across this project.
However fast skimming website let me to "open source" phrases but no legal binding specifics about licensing.

Could you please consider adding some permissive (like Public Domain, MIT or BSD or Apache) license to this project?
IMHO Adding it to root of repository as LICENSE file will be canonical and easiest to spot.
Thanks!
Greg

**Comment by fdb** [comment]
Fixed by e41ced1672f5ab4c23aeb5807b734b285fc924a0.
